name: nf-crispriseq

channels:
    - conda-forge
    - bioconda

dependencies:
    - python=3.12
    - pip
    - bioconda::eggnog-mapper>=2.1.13
    - bioconda::fastqc
    - bioconda::perl-uri
    - bioconda::seqtk
    - bioconda::sra-tools
    - bioconda::umi_tools=1.1.6
    - conda-forge::git
    - conda-forge::pigz
    - conda-forge::unzip
    - pip:
        - "git+https://github.com/scbirlab/crispio.git@fitness#egg=crispio[fit_cuda_local]"
        - 'carabiner-tools[mpl,pd]>=0.0.4'
        - 'cutadapt>=5.0'
        - 'multiqc>=1.27'
